spring:
  # 로컬 개발용 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/party?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver